### ISSUE TITLE
Question about About the initialization of GGNN in ggnn_baseline.py

### ISSUE THREAD

**Issue by tingzou123** [thilinicooray/context-aware-reasoning-for-sr#1]
hello, I am reading your code, but I find that you initial the node of GGNN in this way （followed below)
`       
        # repeat single image for max role count a frame can have
        img = v

        img = img.expand(self.encoder.max_role_count, img.size(0), img.size(1)) # 扩展维度到maxcount*m*n

        img = img.transpose(0,1) 
        img = img.contiguous().view(batch_size * self.encoder.max_role_count, -1)

        verb_embd = self.verb_emb(gt_verb) 
        role_embd = self.role_emb(role_idx) 
        role_embd = role_embd.view(batch_size * self.encoder.max_role_count, -1) 

        verb_embed_expand = verb_embd.expand(self.encoder.max_role_count, verb_embd.size(0), verb_embd.size(1))
        verb_embed_expand = verb_embed_expand.transpose(0,1)
        verb_embed_expand = verb_embed_expand.contiguous().view(batch_size * self.encoder.max_role_count, -1)

        input2ggnn = img * role_embd * verb_embed_expand `
it seemed that you don't use the features from **CNN of verb** described by that work(followed by)
![image](https://user-images.githubusercontent.com/49507984/99679475-f3585900-2ab6-11eb-912d-d5caff3440c3.png)
So i am confused about this, could you give me some explain about your thinking

**Comment by thilinicooray** [comment]
The performance was further lower when I used features from pretrained CNNs for verb and roles as mentioned in the original paper. Therefore I implemented this way and did a fair comparison with our own work. 
Please note that we do not own any official implementation for the GGNN work as we are not the authors.
