### ISSUE TITLE
question about results

### ISSUE THREAD

**Issue by Ironmankiller** [thilinicooray/context-aware-reasoning-for-sr#4]
I didn't modify any hyper-parameters, but the results of FR model based on TDA and CAQ are worse than those reported in the paper. I wonder if there are some parameters that are different from the default parameters？
![image](https://user-images.githubusercontent.com/35445088/116363375-a59a0680-a835-11eb-9268-0c9390d23e5a.png)
![image](https://user-images.githubusercontent.com/35445088/116363457-bc405d80-a835-11eb-9b17-b33cdec12096.png)

**Comment by thilinicooray** [comment]
Our results were produced with the provided conda environment with its exact dependency versions. May I know whether your environment is the exact same?

**Comment by Ironmankiller** [comment]
> Our results were produced with the provided conda environment with its exact dependency versions. May I know whether your environment is the exact same?

Thank you for your reply. I install the conda environment provided in this project, and now it works!
